name: DigitalWheelie
favicon: null
layout_spectrum: 0.91881
typography_spectrum: 0.14673
title: 'Digital Wheelie - Peace, Love & Pop a Wheelie!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fc6605'
    - '#630263'
    - '#64cb08'
    - '#edbf90'
  brandStrength: 0.75
  lightness: 0.2543162296060473
  saturation: 0.9196792235597968
  rhythmicContrast: 0.825379888061434
purpose: []
